// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Orh6wuAedVnYKcv_9QVCorxFSUN-QgM',
    appId: '1:1057813223258:web:a36983b68db64f4fa9c563',
    messagingSenderId: '1057813223258',
    projectId: 'fanterlino-101',
    authDomain: 'fanterlino-101.firebaseapp.com',
    storageBucket: 'fanterlino-101.firebasestorage.app',
    measurementId: 'G-2ZR67Y27QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-5ytugHkxfqrgYeG7zT6PMMVqhBiEhk',
    appId: '1:1057813223258:android:bc71ec47673bbca4a9c563',
    messagingSenderId: '1057813223258',
    projectId: 'fanterlino-101',
    storageBucket: 'fanterlino-101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClUl4Q1u9iQ9MVDkufY1bmpHpXdtTj4pc',
    appId: '1:1057813223258:ios:0358ec32b85619b9a9c563',
    messagingSenderId: '1057813223258',
    projectId: 'fanterlino-101',
    storageBucket: 'fanterlino-101.firebasestorage.app',
    iosBundleId: 'com.beliverz.portafolioEx1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClUl4Q1u9iQ9MVDkufY1bmpHpXdtTj4pc',
    appId: '1:1057813223258:ios:0358ec32b85619b9a9c563',
    messagingSenderId: '1057813223258',
    projectId: 'fanterlino-101',
    storageBucket: 'fanterlino-101.firebasestorage.app',
    iosBundleId: 'com.beliverz.portafolioEx1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Orh6wuAedVnYKcv_9QVCorxFSUN-QgM',
    appId: '1:1057813223258:web:35544402bfe39053a9c563',
    messagingSenderId: '1057813223258',
    projectId: 'fanterlino-101',
    authDomain: 'fanterlino-101.firebaseapp.com',
    storageBucket: 'fanterlino-101.firebasestorage.app',
    measurementId: 'G-VNVG7Y7JCH',
  );
}
